### ISSUE TITLE
Allow running in the context of CI for a particular repo

### ISSUE THREAD

**Issue by fractaledmind** [MatheusRich/end_of_life#11]
This is a lovely idea, but where I would particularly like to know about EOL Ruby versions is in my CI pipeline for new builds of a repo. Ideally, I could have a configuration file that specifies how far away from EOL I am willing to allow my repo to be, and then the CI action fails my build if it is run too close to the EOL. 

Since you already of the code for finding the min Ruby version for a repo, this feels like a possible extension of this gem. Alternatively, I could imagine forking and creating a different gem focused on this use-case. What are your thoughts?

**Comment by MatheusRich** [comment]
If I understand it correctly, this could be split into two separate issues:

1. Allow searching just a particular repo.
2. Allow specifying the minimum Ruby version considered EOL.

We could use CLI options to solve those:

For 1., we could add an option `--repo=some_user/some_repo`
For 2. `--min-ruby-version=2.7.1`

WDYT?

**Comment by fractaledmind** [comment]
I was imagining rather that (2) would be "Allow specifying the maximum date distance from EOL". So, if Ruby 2.x.x is EOL on April 1, 2022, and the CLI is passed `--max-eol-months-away=2` and today is Jan 1, 2022, everything is ok. But on March 1, 2022, the CLI reports an error as we are now within the 2 month window of the EOL of the found Ruby version in the repo.

But, absolutely on the first issue. And I agree that this could be provided via CLI options. In general, what I love is that the tool can determine the min Ruby version in use and when its EOL is. So, if I can specify a particular repo and a particular window, I can build a CI check that helps the entire team across all apps ensure that we don't run EOL Ruby versions

**Comment by MatheusRich** [comment]
Gotcha. Do you think #7 is what you are looking for on (2)?

**Comment by fractaledmind** [comment]
Sort of. I am fundamentally interested in getting a Yes/No answer to the question: "Can I build this release?" As it stands, this repo provides a CLI tool that answers the question: "What is the state of my repos with regards to Ruby EOLs?"

So, knowing that the EOL for the Ruby version used in some repo is coming up is useful, but what I want for a CI integration is to be able to say: "for this repo and this threshold, should I fail this build or not?" This requires knowing how far away the EOL is from today, but it also requires getting some threshold from the user to allow to determine a Yes/No answer.

**Comment by MatheusRich** [comment]
Currently, the end_of_life doesn't exit with an error code if there is some repo with EOL Ruby. If we changed that, would it help you fail the CI builds?

**Comment by fractaledmind** [comment]
Yes. That is exactly the kind of thing I'm interested in. Not so much a report of the current state of my user's repos. But something I can run in GH Actions or CircleCI to help continuously ensure our suite of apps are being pushed to avoid EOL versions

**Comment by MatheusRich** [comment]
I addressed half of it. I'll close it after we fix 1.

**Comment by MatheusRich** [comment]
@fractaledmind v0.2.0 is released! Now it's possible to do 

```sh
end_of_life --repo user/some-repo
```

to search a specific repository. It will exit with -1 if any repo uses EOL versions.

I think this closes this issue, right?

**Comment by fractaledmind** [comment]
I can open another issue for adding something like `--max-eol-months-away=2`, but this is a massive help already to know to fail builds with current EOL Rubies
