### ISSUE TITLE
Handle incomplete results from GitHub API

### ISSUE THREAD

**Issue by duncan-bayne** [MatheusRich/end_of_life#9]
Currently, incomplete results (i.e. queries that return > 100 repositories) will just generate a warning.  The remaining repositories beyond 100 will be ignored.

**Comment by MatheusRich** [comment]
Yeah, that's correct. For sake of simplicity, I decided to just warn about this in v0.1.0. I'll tackle this soon (unless someone does it first).

**Comment by duncan-bayne** [comment]
I'm hoping to raise a PR for this soon :)
